---
title: "Logistic Regression"
author: "Clinton Moshe"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the Data and packages

```{r data}
library(tidyverse)
library(caret)

AdmData <- read_csv('data/Admission_Predict_Ver1.1.csv')[-1]
str(AdmData)
summary(AdmData)
```

## Data Preparation

```{r data prep}
AdmData_1 <- AdmData %>%
  mutate(
    `University Rating` = as_factor(`University Rating`),
    `Research` = as_factor(`Research`),
    `SOP` = as_factor(`SOP`)
  )
str(AdmData_1)
summary(AdmData_1)

# confirming NA/MISSING DATA
colSums(is.na(AdmData_1))
AdmData_1$`Chance of Admit`

# split the data
AdmData_1$`Chance of Admit` <- ifelse(AdmData_1$`Chance of Admit` >0.7,1,0)

index <- createDataPartition(AdmData_1$`Chance of Admit`,list = FALSE, p=0.8)
index = as_vector(index)
train <- AdmData_1[index,]
test <- AdmData_1[-index,]
```

## Exploratory Data Analaysis

```{r EDA}

```
## Modelling

```{r modelling}
attach(train)
model1 <- glm(`Chance of Admit`~., 
              data = AdmData_1, 
              family = poisson(link = "log"))
summary(model1)
```

## making predictions

```{r predictions}
options(scipen=999)
pred1 <- predict(model1, newdata = test, type = "response")
pred1 <- ifelse(pred1 >=0.7,1,0)

df <- data.frame(pred1, test$`Chance of Admit`)
df
tb <- table(test$`Chance of Admit`, pred1)
confusionMatrix(tb)
```

