---
title: "Predict wine quality using SVM"
author: "Clinton Moshe"
date: "11/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading the data and packages

    We are going to predict the red wine quality using svm. this is going to be classification problem, if the quality of wine is >= 7 we are going to classify as good quality else bad.
    
```{r data and packages}
library(tidyverse)
library(caret)
library(DataExplorer)

wine_quality <- read_csv('data/winequality-red.csv')
summary(wine_quality)
str(wine_quality)

wine_quality$quality <- as.factor(wine_quality$quality)
```

## Analysis eg NA ...

```{r Analysis}
# handling NA values
colSums(is.na(wine_quality))
# plotting NA values
plot_missing(wine_quality)
```

## Exploratory Data Analysis

```{r EDA}
# plotting individual varibales
# alcohol
# skewed
ggplot(data = wine_quality) +
  geom_histogram(aes(alcohol), bins = 20) +
  ggtitle('distribution of alcohol')

# density plot
ggplot(data = wine_quality) +
  geom_density(aes(x=alcohol))

ggplot(data = wine_quality) +
  geom_histogram(aes(log(alcohol)), bins = 20) 

# sulphates
ggplot(data = wine_quality) +
  geom_histogram(aes(sulphates), bins = 20)
# pH
ggplot(data = wine_quality) +
  geom_histogram(aes(pH), bins = 20)
# density
ggplot(data = wine_quality) +
  geom_histogram(aes(density), bins = 20)
# total sulfur dioxide
ggplot(data = wine_quality) +
  geom_histogram(aes(`total sulfur dioxide`), bins = 20)
# free sulfur dioxide
ggplot(data = wine_quality) +
  geom_histogram(aes(`free sulfur dioxide`), bins = 20)
# chlorides
ggplot(data = wine_quality) +
  geom_histogram(aes(chlorides), bins = 20)
# residual sugar
ggplot(data = wine_quality) +
  geom_histogram(aes(`residual sugar`), bins = 20)
# citric acid
ggplot(data = wine_quality) +
  geom_histogram(aes(`citric acid`), bins = 20)
# volatile acidity
ggplot(data = wine_quality) +
  geom_histogram(aes(`volatile acidity`), bins = 20)
# fixed acidity
ggplot(data = wine_quality) +
  geom_histogram(aes(`fixed acidity`), bins = 20)

## box plot
# outliers
ggplot(data = wine_quality)+
  geom_boxplot(aes(y=`fixed acidity`))
```

## Data Splitting

```{r data splitting}
index <- createDataPartition(wine_quality$quality, p=0.75, list = FALSE)
train <- wine_quality[index,]
test <- wine_quality[-index,]
```

## modelling

```{r model1}
# names(getModelInfo())
library(kernlab)
model1 <- train(quality~., data=train, 
                preProcess=c("scale","center"),
                method='svmRadial')
model1

pred1 <- predict(model1, newdata = test)
pred1

confusionMatrix(pred1,test$quality)
```
